# MM-DOCS template: https://github.com/majkinetor/mm-docs-template

version: '{build}'
max_jobs: 1
branches:
  only:
  - master
#build:
#  verbosity: minimal

image: Ubuntu

environment:
  MM_DOCS_VERSION: 0.2.1

init:
- ps: $PSVersionTable

install:
- ps: Install-Module InvokeBuild -Force

build_script:
- ps: Invoke-Build Build

artifacts:
- path: source/site

notifications:
- provider: Email
  to: miodrag.milic@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
