# MM-DOCS template: https://github.com/majkinetor/mm-docs-template

version: '{build}'
max_jobs: 1
branches:
  only:
  - master
#build:
#  verbosity: minimal

image: Visual Studio 2017

environment:
  MM_DOCS_VERSION: 0.2.1

init:
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable

install:
- cinst invoke-build --no-progress
- ps: docker pull majkinetor/mm-docs:$Env:MM_DOCS_VERSION

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'
    Invoke-Build Build

artifacts:
- path: docs/site

notifications:
- provider: Email
  to: miodrag.milic@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
